### ISSUE TITLE
Fails to build against fribidi 1.0.8

### ISSUE THREAD

**Issue by aelmahmoudy** [pediapress/pyfribidi#10]
When building pyfribidi against fribidi 1.0.8, I got the following error:
```
======================================================================
FAIL: testNoReorderNonSpacingMarks (test_pyfribidi.UTF8Tests)
utf8: reorder non spacing marks
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/python-team/modules/pyfribidi/debian/output/pyfribidi-0.12.0+repack/.pybuild/cpython3_3.8/build/test_pyfribidi.py", line 146, in testNoReorderNonSpacingMarks
    self.assertEqual(pyfribidi.log2vis("חַיְפַא", RTL, reordernsm=False),
AssertionError: 'אפַיְחַ' != 'אַפְיַח'
- אפַיְחַ
+ אַפְיַח


======================================================================
FAIL: testNoReorderNonSpacingMarks (test_pyfribidi.UnicodeTests)
unicode: reorder non spacing marks
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/python-team/modules/pyfribidi/debian/output/pyfribidi-0.12.0+repack/.pybuild/cpython3_3.8/build/test_pyfribidi.py", line 90, in testNoReorderNonSpacingMarks
    self.assertEqual(pyfribidi.log2vis(u"חַיְפַא", RTL, reordernsm=False),
AssertionError: 'אפַיְחַ' != 'אַפְיַח'
- אפַיְחַ
+ אַפְיַח
```

I didn't face this issue when building against fribidi 1.0.7

See: https://github.com/fribidi/fribidi/issues/136

**Comment by aelmahmoudy** [comment]
The difference between the two outputs in hex is as follows: 
- d790 d7a4 d6b7 d799 d6b0 d797 d6b7
+ d790 d6b7 d7a4 d6b0 d799 d6b7 d797
